# Generated by Django 5.2.7 on 2025-12-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0002_creation_featured_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='creation',
            name='translation_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
