# Generated by Django 5.2.7 on 2025-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0003_creation_language_creation_translation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
