# Generated by Django 5.2.7 on 2025-12-20 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0004_category_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='translation_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
