# Generated by Django 5.2.7 on 2025-11-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiringmessage',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AddField(
            model_name='hiringmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringmessage',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
