# Generated by Django 5.2.7 on 2025-11-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subskill',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subskill',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
