# Generated by Django 5.2.7 on 2025-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
