# Generated by Django 5.2.7 on 2025-12-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('project_detail', 'Project Detail'), ('creations', 'Creations'), ('creation_detail', 'Creation Detail'), ('experience', 'Experience'), ('skills', 'Skills')], max_length=50, unique=True)),
                ('index', models.BooleanField(default=True)),
                ('follow', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('boolean', 'Boolean'), ('number', 'Number'), ('color', 'Color')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SitemapSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50, unique=True)),
                ('include', models.BooleanField(default=True)),
                ('priority', models.FloatField(default=0.5)),
                ('is_public', models.BooleanField(default=True)),
                ('changefreq', models.CharField(default='weekly', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('home', 'Home Page'), ('portfolio', 'Portfolio Page'), ('project_category', 'Project Category'), ('creation_page', 'Creation Page')], max_length=50)),
                ('item_type', models.CharField(max_length=50)),
                ('limit', models.PositiveIntegerField(default=6)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('context', 'item_type')},
            },
        ),
    ]
