# Generated by Django 5.2.7 on 2026-01-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaysetting',
            name='context',
            field=models.CharField(choices=[('home', 'Home Page'), ('portfolio', 'Portfolio Page'), ('project', 'Project'), ('project_category', 'Project Category'), ('creation_page', 'Creation Page'), ('creations_category', 'Creations Category'), ('creations_type', 'Creations Type')], max_length=50),
        ),
        migrations.AlterField(
            model_name='displaysetting',
            name='item_type',
            field=models.CharField(choices=[('creations', 'Creations'), ('experience', 'Experience'), ('project', 'Project'), ('qualifications', 'Qualifications'), ('services', 'Services'), ('skills', 'Skills'), ('socialmedias', 'Social Medias')], max_length=50),
        ),
        migrations.AlterField(
            model_name='seopagesetting',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('project_detail', 'Project Detail'), ('creations', 'Creations'), ('creations_category', 'Creations Category'), ('creations_type', 'Creations Type'), ('creation_detail', 'Creation Detail'), ('experience', 'Experience'), ('skills', 'Skills'), ('qualifications', 'Qualifications'), ('services', 'Services')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sitemapsetting',
            name='changefreq',
            field=models.CharField(choices=[('always', 'Always'), ('hourly', 'Every hour'), ('daily', 'Every day'), ('weekly', 'Every week'), ('monthly', 'every month'), ('yearly', 'every year'), ('never', 'Never')], default='weekly', max_length=20),
        ),
    ]
