# Generated by Django 5.2.7 on 2026-01-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_displaysetting_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemapsetting',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('project_detail', 'Project Detail'), ('creations', 'Creations'), ('creations_category', 'Creations Category'), ('creations_type', 'Creations Type'), ('creation_detail', 'Creation Detail'), ('experience', 'Experience'), ('skills', 'Skills'), ('qualifications', 'Qualifications'), ('services', 'Services')], max_length=50, unique=True),
        ),
    ]
