# Generated by Django 5.2.7 on 2025-10-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='description',
            field=models.CharField(default='nice', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='location',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='school_url',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
