# Generated by Django 5.2.7 on 2025-11-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0002_qualification_description_qualification_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
