# Generated by Django 5.2.7 on 2025-12-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0003_qualification_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='school_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
