# Generated by Django 5.2.7 on 2025-12-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=50)),
                ('headline', models.CharField(help_text='Short role/title e.g. Full Stack Developer', max_length=255)),
                ('short_intro', models.TextField(help_text='Hero section description')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('profile_image_alt', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(blank=True, help_text='Upload resume (PDF)', null=True, upload_to='profile/')),
                ('resume_alt', models.CharField(blank=True, max_length=100)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('about_image_alt', models.CharField(blank=True, max_length=100)),
                ('about_text', models.TextField(help_text='About section main text')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('keywords', models.JSONField(blank=True, default=list, help_text="SEO keywords for profile (e.g. ['developer', 'django', 'react'])")),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
