# Generated by Django 5.2.7 on 2025-12-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
