# Generated by Django 5.2.7 on 2025-10-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('organization_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
