# Generated by Django 5.2.7 on 2025-11-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
